{% set name = "LFPy" %}
{% set version = "2.2.6" %}
{% set build = 0 %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/lfpy/{{ name }}-{{ version }}.tar.gz
  sha256: 105046db3628c6f72a6ab96ee8ac0f4833bf8eee428dcee50cb7f2926b755966

build:
  number: {{ build }}
  {% set mpi_prefix = "mpi_" + mpi %} # use mpi_*` neuron variant
  string: {{ mpi_prefix }}_py{{ py }}h{{ PKG_HASH }}_{{ build }}
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make  # [linux]
  host:
    - python
    - pip
    - cython >=0.20
    - numpy >=1.8
    - neuron
    - {{ mpi }}
    - lfpykit >=0.4
  run:
    - python
    - setuptools
    - cython >=0.20
    - {{ pin_compatible('numpy') }}
    - scipy >=0.14
    - h5py >=2.5
    - hdf5  # [linux and mpi == "openmpi"]  # workaround for https://github.com/conda-forge/h5py-feedstock/issues/103
    - mpi4py >=1.2
    - {{ mpi }}
    - {{ pin_compatible('neuron') }}  {{ mpi_prefix }}_*
    - lfpykit >=0.4
    - ncurses
    - readline

test:
  requires:
    - openssh  # [mpi == "openmpi"]
    - pytest
  imports:
    - LFPy
  commands:
    - py.test -vsx --pyargs LFPy

about:
  home: https://github.com/LFPy/LFPy
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: LFPy is a Python-module for calculation of extracellular potentials from multicompartment neuron models

  description: |
    LFPy provides a set of easy-to-use Python classes for setting up your
    model, running your simulations and calculating the extracellular
    potentials arising from activity in your model neuron. If you have a model
    working in NEURON or NeuroML2 already, it is likely that it can be adapted
    to work with LFPy.

  doc_url: https://lfpy.readthedocs.io
  dev_url: https://github.com/LFPy/LFPy

extra:
  recipe-maintainers:
    - espenhgn
    - minrk
