{% set name = 'LFPy' %}
{% set version = "2.0.4" %}
{% set build = 0 %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/lfpy/{{ name }}-{{ version }}.tar.gz
  sha256: a66c1d62581348bc0a0d96abf805611fca4c7779ac92b421165d9f666e8cc26c

build:
  number: {{ build }}
  {% set mpi_prefix = "mpi_" + mpi %} # use mpi_*` neuron variant
  string: "{{ mpi_prefix }}_py{{ py }}h{{ PKG_HASH }}_{{ build }}"
  script: "{{PYTHON}} -m pip install . --no-deps -vv"
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython >=0.20
    - numpy >=1.8
    - neuron
    - {{ mpi }}
  run:
    - python
    - setuptools
    - cython >=0.20
    - {{ pin_compatible('numpy') }}
    - scipy >=0.14
    - h5py >=2.5
    - mpi4py >=1.2
    - {{ mpi }}
    - neuron >=7.6.7 {{ mpi_prefix }}_*

test:
  requires:
    # test with mpich instead of openmpi
    # mpi4py with openmpi doesn't import on CI
    # without extra environment variables set
    # - mpich
    - pytest
  imports:
    - LFPy
  commands:
    - py.test -vsx --pyargs LFPy

about:
  home: https://github.com/LFPy/LFPy
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: 'LFPy is a Python-module for calculation of extracellular potentials from multicompartment neuron models'

  description: |
    LFPy provides a set of easy-to-use Python classes for setting up your
    model, running your simulations and calculating the extracellular
    potentials arising from activity in your model neuron. If you have a model
    working in NEURON or NeuroML2 already, it is likely that it can be adapted
    to work with LFPy.

  doc_url: https://lfpy.readthedocs.io
  dev_url: https://github.com/LFPy/LFPy

extra:
  recipe-maintainers:
    - espenhgn
    - minrk
